stages:          # List of stages for jobs, and their order of execution
  - zip
  - upload
  - release

variables:
  PLASMOID_PKG: "advancedreboot-${CI_COMMIT_TAG}.plasmoid"
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/advancedreboot/${PLASMOID_PKG}"

zip_job:
  stage: zip
  image: debian:latest
  rules:
    - if: $CI_COMMIT_TAG                 # Run this job when a tag is created
  artifacts:
    paths:
      - plasmoid/${PLASMOID_PKG}
  before_script:
    - apt-get update
    - apt-get install -q -y --no-install-recommends zip
  script:
    - echo "Creating Plasmoid file"
    - cd plasmoid
    - zip -r ${PLASMOID_PKG} metadata.json assets/ contents/

upload:
  stage: upload
  image: curlimages/curl:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file plasmoid/${PLASMOID_PKG} "${PACKAGE_REGISTRY_URL}"

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG                 # Run this job when a tag is created
  script:
    - echo "Performing release job"
  release:                               # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG_MESSAGE'
    assets:
      links:
        - name: 'Package release $CI_COMMIT_TAG'
          url: '${PACKAGE_REGISTRY_URL}'
          link_type: "package" 
