stages:          # List of stages for jobs, and their order of execution
  - build-i18n

translate-job:       # This job runs in the build stage, which runs first.
  image: debian:latest
  stage: build-i18n
  before_script:
    - apt-get update
    - apt-get install -q -y --no-install-recommends gettext git apt-transport-https ca-certificates
    - sudo update-ca-certificates
  script:
    - git clone https://gitlab.com/scias/plasma-advancedreboot
    - echo "Updating translation files..."
    - cd plasma-advancedreboot/plasmoid/translate
    - bash ./merge
    - bash ./build
    - git status
