stages:          # List of stages for jobs, and their order of execution
  - zip
  - release

zip_job:
  stage: zip
  image: debian:latest
  rules:
    - if: $CI_COMMIT_TAG                 # Run this job when a tag is created
  artifacts:
    paths:
      - advancedreboot-$CI_COMMIT_TAG.plasmoid
  before_script:
    - apt-get update
    - apt-get install -q -y --no-install-recommends zip
  script:
    - echo "Creating Plasmoid file"
    - cd plasmoid
    - zip -r advancedreboot-$CI_COMMIT_TAG.plasmoid metadata.json assets/ contents/

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG                 # Run this job when a tag is created
  script:
    - echo "Performing release job"
  release:                               # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG_MESSAGE'
    assets:
      links:
        - name: 'asset1'
          url: 'https://example.com/assets/1'
          link_type: "package" 
